#!/bin/bash
set -e

case "$1" in
    configure)
        # Create system user if needed
        if ! getent passwd second-hand > /dev/null; then
            adduser --system --group --no-create-home \
                    --home /nonexistent \
                    --shell /usr/sbin/nologin second-hand
        fi
        ;;
esac

#DEBHELPER#
